USE KODILLA_COURSE;

CREATE TABLE STATS (
	STAT_ID INT(11) NOT NULL AUTO_INCREMENT,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL,
    PRIMARY KEY (STAT_ID)
);