USE KODILLA_COURSE;

DROP EVENT IF EXISTS SAVE_STAT;

DELIMITER $$ 

CREATE EVENT SAVE_STAT
	ON SCHEDULE EVERY 1 MINUTE
    DO 
    BEGIN
		DECLARE BESTSELL_COUNT INT DEFAULT 0;
		CALL UpdateBestsellers();
        SELECT * FROM BESTSELLERS_COUNT INTO BESTSELL_COUNT;
		INSERT INTO STATS (STAT_DATE, STAT, VALUE)
			VALUES (CURTIME(), "BESTSELLERS", BESTSELL_COUNT);
	END $$

DELIMITER ;

COMMIT;