SELECT U.NAME, P.SUMMARY 
FROM ISSUESLISTS U, ISSUES P
WHERE U.ID = P.ISSUESLIST_ID;

SELECT U.DESCRIPTION, P.FIRSTNAME, P.LASTNAME 
FROM ISSUES U, USERS P
WHERE U.USER_ID_ASSIGNEDTO = P.ID;

SELECT USER_ID_ASSIGNEDTO, COUNT(*) AS NUMBER_OF_TASKS
FROM ISSUES 
GROUP BY USER_ID_ASSIGNEDTO
HAVING COUNT(*) > 0;